### ISSUE TITLE
Brainstorm about non-map possibilities

### ISSUE THREAD

**Issue by smai-f** [code-for-montana/nonprofit-data#12]
Per meeting with MNA on 12/12, a map seems like a reasonable way to be the informational tool MNA wants, but none of us are 100% sold that it's the _best_ solution. Do some brainstorming about what the map experience could look like if not a straight up map with address pins.

**Comment by elderferreiras** [comment]
In which situation would a map be more attractive to someone looking for a list of non-profits than an actual list? 

I can see myself zooming into Billings, MT, for example, to find non-profits in the area, but I also could see myself entering a zip code or a city to get a list.

I also think having a list and a map works well, like Zillow. If you don't want to see a map, then you move an "ellipsis" to the right until the map is gone kind of thing.

In the future, this could make it easy to display the system in a cellphone because we could hide the map and display the list if you're opening it in a small device.

![Wireframe](https://euelderf.s3-us-west-2.amazonaws.com/code-for-montana/wireframe.png)

**Comment by smai-f** [comment]
@elderferreiras I love the way you sketched that, and thank you so much for putting time and effort into this! It's wonderful especially because everything you've outlined here is pretty much the consensus we came to when we met in person this week :) Right down to the expand/collapse option of the left sidebar.

The big notable change is that we are no longer putting a "pin" at each address location of nonprofits. Instead we are going to use D3 and do more of a data visualization/aggregation for a couple reasons: 
1. The UX of having map pins when there are literally thousands of organizations in the bigger Montana communities is challenging, 
2.) It is a privacy concern to map addresses when the data on the 990 may include people's private residences. 

I'm going to count this as completed because we have a solid plan around what we're going to do at different zoom views:

```
Three zoom levels
State - county lines w/ circle marks representing # of nonprofits, as data is filtered w/ number text label. With tooltips
County - County boundary. Neighbor counties shown (click to shift view to that county). Within selected county: circles for each distinct post office/address city w/ nonprofit counts as circle mark and text label. Plus tooltips, probably
City level: D3 bubble chart showing nonprofits by category, e.g. https://github.com/UsabilityEtc/d3-country-bubble-chart. Plus tooltips
```

We also sketched some general UX in this document similar to your diagrams: https://docs.google.com/document/d/1JrVz6Tna--lqtwwPBaTj4-Sw2Iw0ikA6KfzdeeEIJvs/edit#heading=h.wy69oofss1dh
